DISTRICTS = [
    {
        "id": "downtown",
        "name": "Downtown Core",
        "lat": 41.8827,
        "lon": -87.6233,
        "radius_km": 2.0,
        "subreddits": ["chicago", "ChicagoLounge"],
        "keywords": ["downtown", "loop", "michigan avenue", "millennium park"],
        "color": "#bf3b2e",
    },
    {
        "id": "midtown",
        "name": "Midtown East",
        "lat": 41.8950,
        "lon": -87.6100,
        "radius_km": 1.5,
        "subreddits": ["chicago"],
        "keywords": ["river north", "streeterville", "navy pier"],
        "color": "#a85500",
    },
    {
        "id": "harbor",
        "name": "Harbor District",
        "lat": 41.8700,
        "lon": -87.6150,
        "radius_km": 1.8,
        "subreddits": ["chicago"],
        "keywords": ["south loop", "museum campus", "grant park"],
        "color": "#a85500",
    },
    {
        "id": "arts",
        "name": "Arts Quarter",
        "lat": 41.9000,
        "lon": -87.6350,
        "radius_km": 1.5,
        "subreddits": ["chicago", "ChicagoArtScene"],
        "keywords": ["wicker park", "bucktown", "ukrainian village"],
        "color": "#6b3fa0",
    },
    {
        "id": "financial",
        "name": "Financial Row",
        "lat": 41.8780,
        "lon": -87.6350,
        "radius_km": 1.2,
        "subreddits": ["chicago"],
        "keywords": ["lasalle street", "financial district", "board of trade"],
        "color": "#1a4fa0",
    },
    {
        "id": "westside",
        "name": "Westside Park",
        "lat": 41.8850,
        "lon": -87.6600,
        "radius_km": 2.0,
        "subreddits": ["chicago", "HumPark"],
        "keywords": ["humboldt park", "west side", "garfield park"],
        "color": "#1d6b3e",
    },
    {
        "id": "university",
        "name": "University Hill",
        "lat": 41.7900,
        "lon": -87.5990,
        "radius_km": 1.8,
        "subreddits": ["uchicago", "chicago"],
        "keywords": ["hyde park", "university of chicago", "kenwood"],
        "color": "#1a4fa0",
    },
    {
        "id": "market",
        "name": "Market District",
        "lat": 41.8840,
        "lon": -87.6550,
        "radius_km": 1.5,
        "subreddits": ["chicago"],
        "keywords": ["west loop", "fulton market", "randolph street"],
        "color": "#bf3b2e",
    },
]

DISTRICT_POSITIONS = {
    "downtown":   {"x": 0.50, "y": 0.40, "r": 62},
    "midtown":    {"x": 0.65, "y": 0.34, "r": 48},
    "harbor":     {"x": 0.37, "y": 0.62, "r": 52},
    "arts":       {"x": 0.73, "y": 0.55, "r": 40},
    "financial":  {"x": 0.42, "y": 0.29, "r": 46},
    "westside":   {"x": 0.21, "y": 0.44, "r": 50},
    "university": {"x": 0.60, "y": 0.70, "r": 44},
    "market":     {"x": 0.27, "y": 0.27, "r": 43},
}

DISTRICT_MAP = {d["id"]: d for d in DISTRICTS}
